//! OUI (Organizationally Unique Identifier) lookup — first 3 bytes of MAC address.
//!
//! Uses the full IEEE OUI database (~33K entries) embedded at compile time.
//! Binary search on a sorted array — O(log n), zero runtime dependencies.

// Generated by build.rs from docs/oui.csv
include!(concat!(env!("OUT_DIR"), "/oui_db.rs"));

/// Look up vendor name from MAC address bytes (uses first 3 bytes = OUI).
/// Returns "Random" for locally administered MACs not found in the database.
pub fn oui_lookup(mac: &[u8]) -> &'static str {
    if mac.len() < 3 {
        return "Unknown";
    }
    let key = [mac[0], mac[1], mac[2]];

    // Try database first — some real manufacturers have the LA bit set (MA-M/MA-S blocks)
    match OUI_DB.binary_search_by_key(&key, |(oui, _)| *oui) {
        Ok(idx) => OUI_DB[idx].1,
        Err(_) => "Unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_known_oui() {
        // ASUS (was incorrectly hardcoded as TP-Link before!)
        assert_eq!(oui_lookup(&[0x7C, 0x10, 0xC9, 0x00, 0x00, 0x00]), "ASUS");
        // Intel
        assert_eq!(oui_lookup(&[0xE4, 0xC7, 0x67, 0x01, 0x02, 0x03]), "Intel");
        // Apple
        assert_eq!(oui_lookup(&[0xF0, 0xEE, 0x7A, 0x00, 0x00, 0x00]), "Apple");
    }

    #[test]
    fn test_unknown_oui() {
        assert_eq!(oui_lookup(&[0xFF, 0xFE, 0xFD, 0x00, 0x00, 0x00]), "Unknown");
    }

    #[test]
    fn test_short_mac() {
        assert_eq!(oui_lookup(&[0x7C, 0x10]), "Unknown");
    }

    #[test]
    fn test_db_is_sorted() {
        for window in OUI_DB.windows(2) {
            assert!(
                window[0].0 < window[1].0,
                "OUI_DB not sorted: {:?} >= {:?}",
                window[0].0,
                window[1].0
            );
        }
    }

    #[test]
    fn test_db_has_entries() {
        assert!(OUI_DB.len() > 30_000, "OUI_DB should have 30K+ entries, got {}", OUI_DB.len());
    }
}
